from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Literal, Optional


NodeName = Literal[
    "u3L", "u2L", "u1L",
    "u3R", "u2R", "u1R",
    "mL", "mR",
    "d1L", "d2L", "d3L",
    "d1R", "d2R", "d3R",
]

Chirality = Literal["L", "R"]
Sign = Literal["+", "-"]


ADJ: Dict[NodeName, List[NodeName]] = {
    "u3L": ["u2L"],
    "u2L": ["u3L", "u1L"],
    "u1L": ["u2L", "u1R", "mL"],

    "u3R": ["u2R"],
    "u2R": ["u3R", "u1R"],
    "u1R": ["u2R", "u1L", "mR"],

    "mL": ["u1L", "d1L", "mR"],
    "mR": ["u1R", "d1R", "mL"],

    "d1L": ["mL", "d1R", "d2L"],
    "d2L": ["d1L", "d3L"],
    "d3L": ["d2L"],

    "d1R": ["mR", "d1L", "d2R"],
    "d2R": ["d1R", "d3R"],
    "d3R": ["d2R"],
}

HUB_SIGN: Dict[NodeName, Sign] = {
    "u1L": "+",
    "u1R": "+",
    "d1L": "-",
    "d1R": "-",
}


@dataclass
class Turtle:
    name: str
    chirality: Chirality
    node: NodeName
    heading: Optional[NodeName] = None
    seen_nodes: List[NodeName] = field(default_factory=list)
    bumps: int = 0
    shared_tokens: List[str] = field(default_factory=list)
    face_tokens: List[str] = field(default_factory=list)
    carry_sign: Optional[Sign] = None
    site_sign_history: List[Sign] = field(default_factory=list)
    mismatch_count: int = 0
    carried_stress: int = 0

    def visit(self) -> None:
        if self.node not in self.seen_nodes:
            self.seen_nodes.append(self.node)


@dataclass
class Collision:
    tick: int
    node: NodeName
    kind: str
    turtles: List[str]
    face_event: str
    incoming_signs: Dict[str, Optional[Sign]]
    outgoing_signs: Dict[str, Optional[Sign]]
    incoming_stress: Dict[str, int]
    outgoing_stress: Dict[str, int]
    incoming_mismatch: Dict[str, int]
    outgoing_mismatch: Dict[str, int]


@dataclass
class HubLedger:
    plus_arrivals: int = 0
    minus_arrivals: int = 0
    unsigned_arrivals: int = 0
    mismatch_events: int = 0
    transfers: int = 0
    clean_closures: int = 0
    tension_closures: int = 0
    stored_tension: int = 0
    stress_energy: int = 0
    deposited_stress: int = 0


@dataclass
class World:
    turtles: Dict[str, Turtle]
    tick: int = 0
    collisions: List[Collision] = field(default_factory=list)
    hub_ledger: Dict[NodeName, HubLedger] = field(
        default_factory=lambda: {hub: HubLedger() for hub in HUB_SIGN}
    )


def classify_collision(names: List[str], world: World) -> str:
    kinds = "".join(sorted(world.turtles[n].chirality for n in names))
    if kinds == "LL":
        return "LL"
    if kinds == "LR":
        return "LR"
    if kinds == "LLR":
        return "LLR"
    return kinds


def triad_induced_mismatch(node: NodeName, incoming_signs: Dict[str, Optional[Sign]]) -> Dict[str, int]:
    """
    Local mismatch generated by a triad as it closes at a signed hub.

    Current toy rule:
    - if a turtle already carries the hub sign, it induces no new mismatch
    - if a turtle carries a non-hub sign, it induces one mismatch
    - unsigned turtles induce no mismatch here
    """
    hub_sign = HUB_SIGN.get(node)
    if hub_sign is None:
        return {name: 0 for name in incoming_signs}

    induced: Dict[str, int] = {}
    for name, sign in incoming_signs.items():
        induced[name] = 1 if sign is not None and sign != hub_sign else 0
    return induced


def triad_burden(node: NodeName, incoming_signs: Dict[str, Optional[Sign]], incoming_mismatch: Dict[str, int]) -> int:
    """
    Candidate local burden functional.

    Present sketch:
    burden = prior mismatch residue + mismatch induced locally by sign incoherence.
    """
    induced = triad_induced_mismatch(node, incoming_signs)
    return sum(incoming_mismatch.values()) + sum(induced.values())


def triad_closure_class(
    node: NodeName,
    incoming_signs: Dict[str, Optional[Sign]],
    incoming_mismatch: Dict[str, int],
) -> str:
    """
    Closure class at a signed hub.

    Current extracted rule:
    - triads at signed hubs always close
    - closure is clean iff burden is zero
    - otherwise closure is tensioned
    """
    hub_sign = HUB_SIGN.get(node)
    if hub_sign is None:
        return "backpressure_bundle"
    burden = triad_burden(node, incoming_signs, incoming_mismatch)
    suffix = "closed" if burden == 0 else "tension"
    return f"ABC{hub_sign}_{suffix}"


def face_event_for(
    kind: str,
    node: NodeName,
    world: World,
    incoming_signs: Dict[str, Optional[Sign]],
    incoming_mismatch: Dict[str, int],
) -> str:
    hub_sign = HUB_SIGN.get(node)
    if hub_sign is not None:
        if kind == "LL":
            return f"B{hub_sign}"
        if kind == "LR":
            return f"sign_transfer{hub_sign}"
        if kind == "LLR":
            return triad_closure_class(node, incoming_signs, incoming_mismatch)

    if kind == "LL":
        return "support_pair"
    if kind == "LR":
        return "complement_exchange"
    if kind == "LLR":
        return "backpressure_bundle"
    return "unknown"


def deposit_carried_stress(world: World, node: NodeName, names: List[str]) -> None:
    ledger = world.hub_ledger.get(node)
    if ledger is None:
        return
    for name in names:
        turtle = world.turtles[name]
        if turtle.carried_stress > 0:
            ledger.deposited_stress += turtle.carried_stress
            ledger.stress_energy += turtle.carried_stress


def update_site_sign_history(world: World, node: NodeName, names: List[str]) -> None:
    hub_sign = HUB_SIGN.get(node)
    if hub_sign is None:
        return
    for name in names:
        world.turtles[name].site_sign_history.append(hub_sign)


def record_hub_arrivals(world: World, node: NodeName, names: List[str], incoming_signs: Dict[str, Optional[Sign]]) -> None:
    ledger = world.hub_ledger.get(node)
    if ledger is None:
        return
    for name in names:
        sign = incoming_signs[name]
        if sign == "+":
            ledger.plus_arrivals += 1
        elif sign == "-":
            ledger.minus_arrivals += 1
        else:
            ledger.unsigned_arrivals += 1


def apply_induced_mismatch(
    world: World,
    node: NodeName,
    names: List[str],
    incoming_signs: Dict[str, Optional[Sign]],
) -> None:
    ledger = world.hub_ledger.get(node)
    if ledger is None:
        return

    induced = triad_induced_mismatch(node, incoming_signs)
    for name in names:
        delta = induced[name]
        if delta > 0:
            world.turtles[name].mismatch_count += delta
            ledger.mismatch_events += delta
            ledger.stress_energy += delta


def mutate_signs(
    world: World,
    node: NodeName,
    names: List[str],
    kind: str,
    incoming_signs: Dict[str, Optional[Sign]],
) -> None:
    hub_sign = HUB_SIGN.get(node)
    if hub_sign is None:
        return

    turtles = [world.turtles[name] for name in names]

    if kind == "LL":
        for turtle in turtles:
            turtle.carry_sign = hub_sign
        return

    if kind == "LR":
        carried = next((incoming_signs[name] for name in names if incoming_signs[name] is not None), hub_sign)
        for turtle in turtles:
            turtle.carry_sign = carried
        world.hub_ledger[node].transfers += 1
        return

    if kind == "LLR":
        for turtle in turtles:
            turtle.carry_sign = hub_sign
        return


def propagate_stress_to_turtles(world: World, names: List[str], face_event: str) -> None:
    if face_event.endswith("_tension"):
        for name in names:
            world.turtles[name].carried_stress += 1
    elif face_event.endswith("_closed"):
        for name in names:
            if world.turtles[name].carried_stress > 0:
                world.turtles[name].carried_stress -= 1


def update_hub_closure_stats(world: World, node: NodeName, face_event: str) -> None:
    ledger = world.hub_ledger.get(node)
    if ledger is None:
        return

    if face_event.endswith("_closed"):
        ledger.clean_closures += 1
        if ledger.stored_tension > 0:
            ledger.stored_tension -= 1
        if ledger.stress_energy > 0:
            ledger.stress_energy -= 1
    elif face_event.endswith("_tension"):
        ledger.tension_closures += 1
        ledger.stored_tension += 1
        ledger.stress_energy += 1


def merge_seen_and_faces(world: World, names: List[str]) -> tuple[List[NodeName], List[str]]:
    union_seen: List[NodeName] = []
    union_faces: List[str] = []

    for name in names:
        turtle = world.turtles[name]
        for seen in turtle.seen_nodes:
            if seen not in union_seen:
                union_seen.append(seen)
        for face in turtle.face_tokens:
            if face not in union_faces:
                union_faces.append(face)

    return union_seen, union_faces


def stamp_collision_tokens(
    world: World,
    names: List[str],
    node: NodeName,
    kind: str,
    face_event: str,
    union_seen: List[NodeName],
    union_faces: List[str],
) -> None:
    token = f"{kind}@{node}"
    face_token = f"{face_event}@{node}"

    for name in names:
        turtle = world.turtles[name]
        turtle.bumps += 1
        turtle.shared_tokens.append(token)
        turtle.seen_nodes = union_seen.copy()
        face_list = union_faces.copy()
        if face_token not in face_list:
            face_list.append(face_token)
        turtle.face_tokens = face_list


def apply_collision(world: World, node: NodeName, names: List[str]) -> None:
    kind = classify_collision(names, world)

    incoming_signs = {name: world.turtles[name].carry_sign for name in names}
    incoming_stress = {name: world.turtles[name].carried_stress for name in names}
    incoming_mismatch = {name: world.turtles[name].mismatch_count for name in names}

    union_seen, union_faces = merge_seen_and_faces(world, names)

    deposit_carried_stress(world, node, names)
    update_site_sign_history(world, node, names)
    record_hub_arrivals(world, node, names, incoming_signs)
    apply_induced_mismatch(world, node, names, incoming_signs)
    mutate_signs(world, node, names, kind, incoming_signs)

    face_event = face_event_for(kind, node, world, incoming_signs, incoming_mismatch)
    stamp_collision_tokens(world, names, node, kind, face_event, union_seen, union_faces)

    propagate_stress_to_turtles(world, names, face_event)
    update_hub_closure_stats(world, node, face_event)

    outgoing_signs = {name: world.turtles[name].carry_sign for name in names}
    outgoing_stress = {name: world.turtles[name].carried_stress for name in names}
    outgoing_mismatch = {name: world.turtles[name].mismatch_count for name in names}

    world.collisions.append(
        Collision(
            tick=world.tick,
            node=node,
            kind=kind,
            turtles=names.copy(),
            face_event=face_event,
            incoming_signs=incoming_signs,
            outgoing_signs=outgoing_signs,
            incoming_stress=incoming_stress,
            outgoing_stress=outgoing_stress,
            incoming_mismatch=incoming_mismatch,
            outgoing_mismatch=outgoing_mismatch,
        )
    )


def detect_collisions(world: World) -> set[str]:
    by_node: Dict[NodeName, List[str]] = {}
    for name, turtle in world.turtles.items():
        by_node.setdefault(turtle.node, []).append(name)

    collided: set[str] = set()
    for node, names in by_node.items():
        if len(names) >= 2:
            collided.update(names)
            apply_collision(world, node, sorted(names))
    return collided


def apply_travel_damping(world: World, previous_nodes: Dict[str, NodeName], collided: set[str]) -> None:
    for name, turtle in world.turtles.items():
        moved = previous_nodes[name] != turtle.node
        if moved and name not in collided and turtle.carried_stress > 0:
            turtle.carried_stress -= 1


def step(world: World, scripted: Dict[str, NodeName]) -> None:
    world.tick += 1
    previous_nodes = {name: turtle.node for name, turtle in world.turtles.items()}

    for name, turtle in world.turtles.items():
        turtle.visit()
        target = scripted[name]
        if target not in ADJ[turtle.node] and target != turtle.node:
            raise ValueError(f"Illegal scripted move for {name}: {turtle.node} -> {target}")
        turtle.heading = target

    for turtle in world.turtles.values():
        turtle.node = turtle.heading  # type: ignore[assignment]
        turtle.visit()

    collided = detect_collisions(world)
    apply_travel_damping(world, previous_nodes, collided)
